server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:localhost.p12
        key-store-password: ${KEYSTORE_PASSWORD} 
        key-store-type: PKCS12
    http2:
        enabled: true